# This file tells Kubernetes what to deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api-deployment  # The name for this deployment
spec:
  replicas: 1  # Tell Kubernetes to run 1 copy (pod) of our container
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
      - name: health-api-container
        image: health-api:v1   # <-- This is the name of the image we built!
        imagePullPolicy: IfNotPresent # <-- Tells K8s to use the local image, not pull from the internet
        ports:
        - containerPort: 5000  # The port our Flask app is running on

---
# This second part creates a "Service" to expose our app
apiVersion: v1
kind: Service
metadata:
  name: health-api-service   # The name for the service
spec:
  type: NodePort  # This type is the easiest way to access our app from outside Minikube
  selector:
    app: health-api  # This links the service to our deployment above
  ports:
  - protocol: TCP
    port: 5000       # The port inside the cluster
    targetPort: 5000 # The port on our container
    nodePort: 30001  # <-- This is the port we will use to access our app!